travis:
  secure:
    BINSTAR_TOKEN: r/k94X+MIXRKjPz4qCa47DGM2Y7pHpdvflh+yfpOt/9tH2ckJJ8YlbyRUnU2Gk1fn4FcwvS1l5zxegjr6v2OMhoEnRkOoMEfGwUzKG5yzzilhO2R0pAdgt5SvkReocs/1IVUtVZOqdZMAdQ5PUzEUpn+9BWAAHaFQIryMn6ukk69oRkFg5NuhLhJCzLpJHGkIGWzfUvVr0lSYetJ6kouAscqmKK1PKAXJLF5gU/Q80+uRWG6rImdxwMUE76U0U7xH5Bp1Bw3BJDu6q8LloqgdWfAhooDnl3KGqeFDM/qCPOH4rHnOT03S9wFqJV/y28UIfz+mlqBgMpJcm/yXM1PRiUFRiUTISnqrd1GOsdEqq8DUElTOboflLZiLDjv309bWVHWxaN2lwzGwbDk4QGuTSa3jOalZGRFgFH6vFQn9HvJ/RxMKJIKf87o2gZuw9UCs9UJc+yHDGOCvJSIpLomjyPfc3sOg82uThfgmaV676VDjwXcgr0XAChtat7g+XQJSh6pWAkYmrzCY+YyAhq969RKpL9/RVbX01581kVPFz4xInTe3ody//JFtm8Eav2FDsfSaspvxUxIr0AW2ssay70+oQqR6ZHbrr3Ngi2hLzEZsljxTB8jVYpzL6Gu3n7Ue8gU6UprcAXE/8t6qBSRY/tYlgiDL0wBTculq43Hkqk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
